# Generated by Django 2.2.5 on 2019-11-04 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='size_x',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='size_y',
            field=models.IntegerField(default=8),
        ),
    ]
