# Generated by Django 2.2.7 on 2019-11-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191104_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_state',
        ),
    ]
