# Generated by Django 2.2.7 on 2019-11-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_game_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_game_state',
            field=models.IntegerField(default=0),
        ),
    ]
