# Generated by Django 2.2.7 on 2019-11-18 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game__game_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='board',
            new_name='_board',
        ),
    ]
