# Generated by Django 2.2.7 on 2019-11-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191118_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='size_x',
            new_name='_size_x',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='size_y',
            new_name='_size_y',
        ),
    ]
