# Generated by Django 2.2.7 on 2019-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191118_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='_game_state',
            new_name='game_state',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='_size_x',
            new_name='size_x',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='_size_y',
            new_name='size_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='_board',
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.CharField(default='', max_length=50),
        ),
    ]
